# Generated by Django 5.2 on 2025-05-20 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='lastmessage_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 20, 14, 2, 25, 423143, tzinfo=datetime.timezone.utc)),
        ),
    ]
